version: '3.1'

services:

  api:
    build:
      context: ./api
    ports:
    - "8082:8080"
    volumes:
      - ./api:/app
    expose:
      - "8080"
    command: [ "node", "server.js" ]
    depends_on:
      - db
  ngrok-api:
    image: wernight/ngrok
    restart: always
    ports:
      - 4042:4040
    environment:
      NGROK_PORT: 'api:8080'
    depends_on:
      - api
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./database:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  ngrok-adminer:
    image: wernight/ngrok
    restart: always
    ports:
      - 4040:4040
    environment:
      NGROK_PORT: 'adminer:8080'
    depends_on:
      - adminer
