version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./database:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  ngrok:
    image: wernight/ngrok
    restart: always
    ports:
      - 4040:4040
    environment:
      NGROK_PORT: 'adminer:8080'
