version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./database:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
